version: "3.9"
services:
  chatgpt-next-web:
    container_name: chatgpt-next-web
    restart: always
    image: registry.gitlab.si.icu/sijinhui/chatgpt-next-web
    build:
      context: .
      dockerfile: Dockerfile
#    ports:
#      - "127.0.0.1:23000:23000"
    network_mode: "host"
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime
