version: "3.9"
services:
  chatgpt-next-web:
    container_name: chatgpt-next-web
#    image: yidadaa/chatgpt-next-web
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/si-private/chatgpt-next-web
#    image: registry.cn-hangzhou.aliyuncs.com/sijinhui/chatgpt-next-web
    build:
      context: .
      dockerfile: Dockerfile
#    depends_on:
#      db:
#        condition: service_healthy
#    ports:
#      - "127.0.0.1:23000:23000"
    network_mode: "host"
    environment:
      - TZ=Asia/Shanghai
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - GOOGLE_URL=$GOOGLE_URL
      - CODE=$CODE
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4
      - GPT_4_BASE_URL=$GPT_4_BASE_URL
      - GPT_4_KEY=$GPT_4_KEY
      - MIDJOURNEY_PROXY_KEY=$MIDJOURNEY_PROXY_KEY
      - MIDJOURNEY_PROXY_URL=$MIDJOURNEY_PROXY_URL
      - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
      - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
      - OPENAI_SB=$OPENAI_SB
      - AZURE_URL=$AZURE_URL
      - AZURE_API_KEY=$AZURE_API_KEY
      - AZURE_API_VERSION=$AZURE_API_VERSION
      - AZURE_VOICE_KEY=$AZURE_VOICE_KEY
      - NEXTAUTH_URL=$NEXTAUTH_URL
      - POSTGRES_PRISMA_URL=$POSTGRES_PRISMA_URL
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
      - AUTH_GITHUB_ID=$AUTH_GITHUB_ID
      - AUTH_GITHUB_SECRET=$AUTH_GITHUB_SECRET
      - EMAIL_SERVER_HOST=$EMAIL_SERVER_HOST
      - EMAIL_SERVER_PORT=$EMAIL_SERVER_PORT
      - EMAIL_SERVER_USER=$EMAIL_SERVER_USER
      - EMAIL_SERVER_PASSWORD=$EMAIL_SERVER_PASSWORD
      - EMAIL_FROM=$EMAIL_FROM
      - SECURE_COOKIES=$SECURE_COOKIES
      - PORT=$PORT
    volumes:
      - /etc/localtime:/etc/localtime
#    networks:
#      - chatgpt-ns
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

#networks:
#  chatgpt-ns:
#    external: true
