name: Monthly Package Cache

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 1 * *'  # 每月1号的凌晨4点

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: node.Dockerfile
          push: true
          tags: sijinhui/node:base
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: cache.Dockerfile
          push: true
          tags: sijinhui/chatgpt-next-web:buildcache
