name: PRO DEPLOY TO TY
on:
  push:
    branches:
      - main
#    paths:
#      - 'app/**'
#      - 'public/**'
#      - '.github/**'
#      - 'docker-compose.yml'
#      - 'Dockerfile'
#      - 'package.json'

jobs:
  build:
    name: build image to aly
    # runs-on: "103.200"
    runs-on: aws
    #    runs-on: ubuntu-latest
    #    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          clean: false
      - name: build and deploy to Docker Hub
        run: |
          echo ${{ secrets.ALY_DOCKER_PASSWORD }} | docker login registry.cn-hangzhou.aliyuncs.com -u ${{ secrets.ALY_DOCKER_USERNAME }} --password-stdin
          echo "${{ secrets.DOCKER_ENV }}" > .env
          bash ./start.sh
          docker-compose build
          docker-compose push
          yes | docker system prune --filter "until=168h"
  deploy:
    name: 部署到服务器
    needs: build
    runs-on: z4
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          clean: true
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Sync repository to ty
        run: |
          yes | docker image prune
          rsync -az -e 'ssh -o StrictHostKeyChecking=no' --delete $GITHUB_WORKSPACE/ root@ty.xiaosi.cc:/data/ChatGPT-Next-Web
      - name: deploy-to-ty
        uses: appleboy/ssh-action@master
        env:
         SERVER_WORKDIR: ${{ secrets.SERVER_WORKDIR }} #传递工作目录变量
        with:
          host: ty.xiaosi.cc #服务器地址
          username: root #用户名
          key: ${{ secrets.SSH_PRIVATE_KEY }} #私钥 安全问题一定都以变量的方式传递！！！
          envs: SERVER_WORKDIR,ALY_DOCKER_PASSWORD,ALY_DOCKER_USERNAME,DOCKER_ENV #使用工作目录变量
          script: |
            cd $SERVER_WORKDIR #进入到工作目录
            echo "${{ secrets.DOCKER_ENV }}" > .env
            echo ${{ secrets.ALY_DOCKER_PASSWORD }} | docker login registry.cn-hangzhou.aliyuncs.com -u ${{ secrets.ALY_DOCKER_USERNAME }} --password-stdin
            docker-compose pull && docker-compose up -d
            yes | docker image prune
            rm -rf /www/server/nginx/proxy_cache_dir/*
            rm -rf /www/server/nginx/proxy_temp_dir/*
            sleep 2
            tccli cdn PurgePathCache --cli-unfold-argument --Paths 'https://chat.xiaosi.cc/' --FlushType delete
      - name: Sync repository to tx
        run: |
          yes | docker image prune
          rsync -az -e 'ssh -o StrictHostKeyChecking=no' --delete $GITHUB_WORKSPACE/ root@tx.xiaosi.cc:/data/ChatGPT-Next-Web
      - name: deploy-to-tx
        uses: appleboy/ssh-action@master
        env:
          SERVER_WORKDIR: ${{ secrets.SERVER_WORKDIR }} #传递工作目录变量
        with:
          host: tx.xiaosi.cc #服务器地址
          username: root #用户名
          key: ${{ secrets.SSH_PRIVATE_KEY }} #私钥 安全问题一定都以变量的方式传递！！！
          envs: SERVER_WORKDIR,ALY_DOCKER_PASSWORD,ALY_DOCKER_USERNAME,DOCKER_ENV #使用工作目录变量
          script: |
            cd $SERVER_WORKDIR #进入到工作目录
            echo "${{ secrets.DOCKER_ENV }}" > .env
            echo ${{ secrets.ALY_DOCKER_PASSWORD }} | docker login registry.cn-hangzhou.aliyuncs.com -u ${{ secrets.ALY_DOCKER_USERNAME }} --password-stdin
            docker-compose pull && docker-compose up -d
            yes | docker image prune
            rm -rf /www/server/nginx/proxy_cache_dir/*
            rm -rf /www/server/nginx/proxy_temp_dir/*
            sleep 2
            tccli cdn PurgePathCache --cli-unfold-argument --Paths 'https://chat.xiaosi.cc/' --FlushType delete
