name: Upstream Sync all branch

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  SyncBranch:
    name: Sync All Branch from latest commits via upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch upstream
        run: |
          echo "Fetching upstream..."
          git remote add upstream https://github.com/Yidadaa/ChatGPT-Next-Web.git
        # if you have a special branch that is protected or any. rename "main", you can exclude it from the synchronization process.
        # the workflow will synchronize all branches from the owner repository except for the "main" branch, providing an example of how it works.
      - name: Set branch list
        id: set-branch-list
        run: |
          echo "Setting branch list..."
          branches=$(git ls-remote --heads https://github.com/Yidadaa/ChatGPT-Next-Web.git | awk -F'/' '{print $NF}')
          branch_list=""
          for branch in $branches; do
            if [[ "$branch" != "main" ]]; then
              branch_list+="$branch,"
            fi
          done
          echo "::set-output name=branch-list::${branch_list%?}"

      - name: Sync branches
        run: |
          branch_list=${{ steps.set-branch-list.outputs.branch-list }}
          IFS=',' read -ra branch_array <<< "$branch_list"
          for branch in "${branch_array[@]}"; do
            echo "Syncing branch: $branch"
            git checkout -B "$branch" --track "upstream/$branch"
            git push origin "$branch"
          done